### ISSUE TITLE
fix noun.csv: animate flag for noun 'старшина' (sergeant-major)

### ISSUE THREAD

**Issue by sszuev** [Badestrand/russian-dictionary#10]
`старшина` (sergeant-major) is animate

[http://gramota.ru/slovari/dic/?word=старшина](http://gramota.ru/slovari/dic/?word=%D1%81%D1%82%D0%B0%D1%80%D1%88%D0%B8%D0%BD%D0%B0)

[https://ru.wiktionary.org/wiki/старшина](https://ru.wiktionary.org/wiki/%D1%81%D1%82%D0%B0%D1%80%D1%88%D0%B8%D0%BD%D0%B0)

```csv
старшина	старшина'	foreman, sergeant-major, master sergeant, petty officer	Hauptfeldwebel; (Ober)maat; Ältester, Oberhaupt (einer Gemeinde)	m		1	0	0	0	старшина'	старшины'	старшине'	старшину'	старшино'й, старшино'ю	старшине'	старшины'	старши'н	старшина'м	старши'н	старшина'ми	старшина'х
```

**Comment by Badestrand** [comment]
Seems to be fixed on the website already https://en.openrussian.org/ru/%D1%81%D1%82%D0%B0%D1%80%D1%88%D0%B8%D0%BD%D0%B0

**Comment by sszuev** [comment]
> Seems to be fixed on the website already https://en.openrussian.org/ru/%D1%81%D1%82%D0%B0%D1%80%D1%88%D0%B8%D0%BD%D0%B0

(possibly it was me who reported this issue on website)

@Badestrand, it would be nice to update the `nouns.csv' file as well.  
You can get the updated version here:
https://github.com/greendatasoft/ru-grammar-tools/blob/master/src/main/resources/nouns.csv

Or I can prepare PR if you don't mind.
