### ISSUE TITLE
fix nouns.csv: list of words that could be added to dictionary

### ISSUE THREAD

**Issue by sszuev** [Badestrand/russian-dictionary#12]
песо: [https://ru.wiktionary.org/wiki/песо](https://ru.wiktionary.org/wiki/%D0%BF%D0%B5%D1%81%D0%BE)
```csv
песо	пе'со	pesos	Peso	n		0	1	0	0
```

**Comment by Badestrand** [comment]
Thanks, added! https://en.openrussian.org/ru/%D0%BF%D0%B5%D1%81%D0%BE
