### ISSUE TITLE
Актуальные данные (Current data)

### ISSUE THREAD

**Issue by keldkemp** [Badestrand/russian-dictionary#15]
@Badestrand, Добрый день!

Последний раз `csv` файлы обновлялись в 2020-09-09. Вы можете сделать актуальную выгрузку? (либо обновить ссылку на актуальную базу)

Так же Вы пишите, что можно посмотреть актуальную базу тут: https://app.togetherdb.com/db/o9puugtgtauo1ih5/russian3/words. Но ссылка не рабочая, можете обновить ее?

**English:**
Hello!

`csv` files were last updated on 2020-09-09. Can you make an actual download? (or update the link to the current database).

You also write that you can see the current database here: https://app.togetherdb.com/db/o9puugtgtauo1ih5/russian3/words. But the link is not working, can you update it?

**Comment by Badestrand** [comment]
Sorry, we don't maintain that dataset on GitHub anymore.

You can access our live database at
https://app.togetherdb.com/db/fwoedz5fvtwvq03v/russian3/words

In the tabs for the tables in the options menu (the three dots) you can
export/download each table.

**Comment by keldkemp** [comment]
Thanks!
