### ISSUE TITLE
Link to dictionary database does not work

### ISSUE THREAD

**Issue by enrico3** [Badestrand/russian-dictionary#17]
Hello,
I get this error message when I click the link:

![image](https://github.com/Badestrand/russian-dictionary/assets/31779179/543705da-5868-437c-aa1c-bb532be8d206)

**Comment by Badestrand** [comment]
Seems like the link is wrong. Should be https://app.togetherdb.com/db/fwoedz5fvtwvq03v/russian3/words

I will check the website.

**Comment by Badestrand** [comment]
Website seems ok. Where did you get that link from? 🙂

**Comment by enrico3** [comment]
That one works, thanks! I got the link from your README.md file here on GitHub 😉 

`We publish the dictionary database via [TogetherDB](https://togetherdb.com) and you can find the database **>>>> [here](**https://app.togetherdb.com/db/o9puugtgtauo1ih5/russian3/words**) <<<<**. You can browse the database tables, sort, filter etc and use the "export" button to download them as CSV.`
