### ISSUE TITLE
illegal separator in line 2677

### ISSUE THREAD

**Issue by cemreefe** [Badestrand/russian-dictionary#5]
[Line 2677 in others.csv](https://github.com/Badestrand/russian-dictionary/blob/1fd608d858f88dd2c2f5fe7ba3a1c4057294caac/others.csv#L2677) reads:
`переборот	перебо'рот	overcome, subdue	Siehe :	переборот (Partizip passiv  m)`
has an unnecessary tab after `siehe :`, which renders it unparsable. After fixing that, the file is parsed just fine.

**Comment by Badestrand** [comment]
Fixed live, actually removed word.
