### ISSUE TITLE
Missing genders in nouns.csv

### ISSUE THREAD

**Issue by defuncart** [Badestrand/russian-dictionary#8]
Firstly thanks very much for [Open Russian](https://de.openrussian.org/) and making the extensive collection of nouns, verbs and adjectives available 

Looking through nouns.csv, I noticed that gender is occasionally missing. For instance, свет (m), право (n) and сын (m). These nouns are not plural only nouns (i.e. ребята), so the genders should be given. These genders are listed on the website ([свет](https://de.openrussian.org/ru/%D1%81%D0%B2%D0%B5%D1%82), [право](https://de.openrussian.org/ru/%D0%BF%D1%80%D0%B0%D0%B2%D0%BE) and [сын](https://de.openrussian.org/ru/%D1%81%D1%8B%D0%BD)), so it seems to be an issue with the csv. These are three examples from the first 100 nouns, potentially there are other similar issues.

**Comment by Badestrand** [comment]
Thank you for the notice!

We now switched to TogetherDB to publish the dataset, see here: https://app.togetherdb.com/db/o9puugtgtauo1ih5/russian3/words (you can download the tables as CSV files with "export").

In the current snapshot the three entries you mentioned are fixed!
